name: monn
description: "Monn is my personal investment tracking and analysis"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.8
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  html: ^0.15.6
  iconoir_flutter: ^7.11.0
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  logger: ^2.6.1
  mockito: ^5.4.4
  path: ^1.9.1
  path_provider: ^2.1.5
  retrofit: ^4.6.0
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  # isar_generator:
  #   version: ^3.1.8
  #   hosted: https://pub.isar-community.dev/
  isar_generator:
    git: 
      url: https://github.com/callumw-k/isar
      ref: v3
      path: packages/isar_generator
  json_serializable: ^6.9.5
  retrofit_generator: ^9.6.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/utils/
  fonts:
    enabled: false
  assets:
    outputs:
      class_name: MonnAssets
    exclude:
      - assets/translations/**

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/crypto/
    - assets/images/icon/
    - assets/images/counter_strike/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/DMSans-Black.ttf
          weight: 900
