name: monn
description: "Monn is my personal investment tracking and analysis"
publish_to: "none"

version: 1.2.1+5

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  iconoir_flutter: ^7.11.0
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  mockito: ^5.4.4
  path: ^1.9.1
  path_provider: ^2.1.5
  retrofit: ^4.6.0
  riverpod_annotation: ^3.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  vector_math: ^2.2.0
  wolt_modal_sheet: ^0.11.0

dev_dependencies:
  build_runner: ^2.4.15
  # custom_lint: ^0.8.1
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  isar_community_generator: ^3.3.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/utils/
  fonts:
    enabled: false
  assets:
    outputs:
      class_name: MonnAssets
    exclude:
      - assets/translations/**

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/crypto/
    - assets/images/icon/
    - assets/images/counter_strike/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/DMSans-Black.ttf
          weight: 900
